:toc-title: 目次
:toc: left
:toclevels: 5

---
title: 相手のスキルを推し量る実用ケース集
tags:
---

== この記事の目的
相手に仕事をお願いするとき、そもそもその人がそのタスクを倒せるスキルを持っているか分からないまま依頼するのは危険だ。

特に、標準やアーキ事といった”別のより多くのタスク郡”のDNAになるような事項を決定するタスクであると、インパクトが極めて大きい。しかも、その人が”自分がわからないことすら分からない”といったこともある。

何かを依頼するときには、能動的に相手のスキルを推し量ることも重要になってくる。見誤ると結局自分に返ってくる。。

== ビジネス編
=== タスク管理できる？
自分のタスク管理ってどうやってる？なにか課題を見つけたらどうする？::
* 自走できるかを確認する

TODOの定義はなんですか？::
* 「何をどのようにいつまでに誰がやるかを決めるまで」は、TODOではないこと

== Excel編
=== Filtered Cells
Question::
あなたはある表を操作しています。そこに条件Aでフィルタを掛け1000行のデータが得られました。この1000行の列Kに対して、別の表から取ってきた1000個の値を上から順に埋めたいと思っています。あなたならどのように処理しますか？

== 技術編
=== テスト
Question:: 
テストって何？(ざっくりした質問により、どのようにこれまでテストをやってきたかが見える。普通の人は明確な定義を持っていないが、これまでの経験から一般化してもらう)

このログイン処理コード何がおかしい？::
* https://qiita.com/YSRKEN/items/0095cf75be3f607b0f98[「世界最悪のログイン処理コード」を解説してみた - Qiita]

=== アプリアーキ
DBの排他・分離レベルを説明して::
* 完璧な回答はいらないが、調べればちゃんと進められることを確認したい

トランザクションって何？::
* 完璧な回答はいらないが、調べればちゃんと進められることを確認したい

例外、エラーハンドリングって何？::
* 完璧な回答はいらないが、調べればちゃんと進められることを確認したい

== SI編
=== 単純作業：テストケースの廃止
前提条件::
* ある処理に対するテストケースが3000ケース存在する
* 3000ケースの内訳は、5ケース1グループである。各グループは対象処理を呼ぶジョブに紐づく（i.e. 1ジョブ5ケース）
* テストケースIDには1から始まる連番が埋め込まれている
* 各ケースに対して、1つのテスト記述書が存在する。ファイル名には、テストケースIDが埋め込まれている

Question::
あるとき、あなたのボスはすべてのグループの3ケース目は論理的に不要であることを決定した。そこであなたに、全てのグループの3ケース目を削除するように依頼した。全てのテスト記述書は1つのフォルダ配下に格納されている。あなたならどうやって対象を削除しますか？